package me.dfzhang.excel.annotation;

/**
 * @ClassName Columns
 * 
 * @Version v1.0
 * @Date 2017年12月7日 上午12:33:08
 * @Author 854154025@qq.com
 * 
 * @Description TODO
 * 
 */
public class Columns {
	/** A={@value} */
	public static final int A = 1;
	/** B={@value} */
	public static final int B = 2;
	/** C={@value} */
	public static final int C = 3;
	/** D={@value} */
	public static final int D = 4;
	/** E={@value} */
	public static final int E = 5;
	/** F={@value} */
	public static final int F = 6;
	/** G={@value} */
	public static final int G = 7;
	/** H={@value} */
	public static final int H = 8;
	/** I={@value} */
	public static final int I = 9;
	/** J={@value} */
	public static final int J = 10;
	/** K={@value} */
	public static final int K = 11;
	/** L={@value} */
	public static final int L = 12;
	/** M={@value} */
	public static final int M = 13;
	/** N={@value} */
	public static final int N = 14;
	/** O={@value} */
	public static final int O = 15;
	/** P={@value} */
	public static final int P = 16;
	/** Q={@value} */
	public static final int Q = 17;
	/** R={@value} */
	public static final int R = 18;
	/** S={@value} */
	public static final int S = 19;
	/** T={@value} */
	public static final int T = 20;
	/** U={@value} */
	public static final int U = 21;
	/** V={@value} */
	public static final int V = 22;
	/** W={@value} */
	public static final int W = 23;
	/** X={@value} */
	public static final int X = 24;
	/** Y={@value} */
	public static final int Y = 25;
	/** Z={@value} */
	public static final int Z = 26;
	/** AA={@value} */
	public static final int AA = 27;
	/** AB={@value} */
	public static final int AB = 28;
	/** AC={@value} */
	public static final int AC = 29;
	/** AD={@value} */
	public static final int AD = 30;
	/** AE={@value} */
	public static final int AE = 31;
	/** AF={@value} */
	public static final int AF = 32;
	/** AG={@value} */
	public static final int AG = 33;
	/** AH={@value} */
	public static final int AH = 34;
	/** AI={@value} */
	public static final int AI = 35;
	/** AJ={@value} */
	public static final int AJ = 36;
	/** AK={@value} */
	public static final int AK = 37;
	/** AL={@value} */
	public static final int AL = 38;
	/** AM={@value} */
	public static final int AM = 39;
	/** AN={@value} */
	public static final int AN = 40;
	/** AO={@value} */
	public static final int AO = 41;
	/** AP={@value} */
	public static final int AP = 42;
	/** AQ={@value} */
	public static final int AQ = 43;
	/** AR={@value} */
	public static final int AR = 44;
	/** AS={@value} */
	public static final int AS = 45;
	/** AT={@value} */
	public static final int AT = 46;
	/** AU={@value} */
	public static final int AU = 47;
	/** AV={@value} */
	public static final int AV = 48;
	/** AW={@value} */
	public static final int AW = 49;
	/** AX={@value} */
	public static final int AX = 50;
	/** AY={@value} */
	public static final int AY = 51;
	/** AZ={@value} */
	public static final int AZ = 52;
	/** BA={@value} */
	public static final int BA = 53;
	/** BB={@value} */
	public static final int BB = 54;
	/** BC={@value} */
	public static final int BC = 55;
	/** BD={@value} */
	public static final int BD = 56;
	/** BE={@value} */
	public static final int BE = 57;
	/** BF={@value} */
	public static final int BF = 58;
	/** BG={@value} */
	public static final int BG = 59;
	/** BH={@value} */
	public static final int BH = 60;
	/** BI={@value} */
	public static final int BI = 61;
	/** BJ={@value} */
	public static final int BJ = 62;
	/** BK={@value} */
	public static final int BK = 63;
	/** BL={@value} */
	public static final int BL = 64;
	/** BM={@value} */
	public static final int BM = 65;
	/** BN={@value} */
	public static final int BN = 66;
	/** BO={@value} */
	public static final int BO = 67;
	/** BP={@value} */
	public static final int BP = 68;
	/** BQ={@value} */
	public static final int BQ = 69;
	/** BR={@value} */
	public static final int BR = 70;
	/** BS={@value} */
	public static final int BS = 71;
	/** BT={@value} */
	public static final int BT = 72;
	/** BU={@value} */
	public static final int BU = 73;
	/** BV={@value} */
	public static final int BV = 74;
	/** BW={@value} */
	public static final int BW = 75;
	/** BX={@value} */
	public static final int BX = 76;
	/** BY={@value} */
	public static final int BY = 77;
	/** BZ={@value} */
	public static final int BZ = 78;
	/** CA={@value} */
	public static final int CA = 79;
	/** CB={@value} */
	public static final int CB = 80;
	/** CC={@value} */
	public static final int CC = 81;
	/** CD={@value} */
	public static final int CD = 82;
	/** CE={@value} */
	public static final int CE = 83;
	/** CF={@value} */
	public static final int CF = 84;
	/** CG={@value} */
	public static final int CG = 85;
	/** CH={@value} */
	public static final int CH = 86;
	/** CI={@value} */
	public static final int CI = 87;
	/** CJ={@value} */
	public static final int CJ = 88;
	/** CK={@value} */
	public static final int CK = 89;
	/** CL={@value} */
	public static final int CL = 90;
	/** CM={@value} */
	public static final int CM = 91;
	/** CN={@value} */
	public static final int CN = 92;
	/** CO={@value} */
	public static final int CO = 93;
	/** CP={@value} */
	public static final int CP = 94;
	/** CQ={@value} */
	public static final int CQ = 95;
	/** CR={@value} */
	public static final int CR = 96;
	/** CS={@value} */
	public static final int CS = 97;
	/** CT={@value} */
	public static final int CT = 98;
	/** CU={@value} */
	public static final int CU = 99;
	/** CV={@value} */
	public static final int CV = 100;
	/** CW={@value} */
	public static final int CW = 101;
	/** CX={@value} */
	public static final int CX = 102;
	/** CY={@value} */
	public static final int CY = 103;
	/** CZ={@value} */
	public static final int CZ = 104;
	/** DA={@value} */
	public static final int DA = 105;
	/** DB={@value} */
	public static final int DB = 106;
	/** DC={@value} */
	public static final int DC = 107;
	/** DD={@value} */
	public static final int DD = 108;
	/** DE={@value} */
	public static final int DE = 109;
	/** DF={@value} */
	public static final int DF = 110;
	/** DG={@value} */
	public static final int DG = 111;
	/** DH={@value} */
	public static final int DH = 112;
	/** DI={@value} */
	public static final int DI = 113;
	/** DJ={@value} */
	public static final int DJ = 114;
	/** DK={@value} */
	public static final int DK = 115;
	/** DL={@value} */
	public static final int DL = 116;
	/** DM={@value} */
	public static final int DM = 117;
	/** DN={@value} */
	public static final int DN = 118;
	/** DO={@value} */
	public static final int DO = 119;
	/** DP={@value} */
	public static final int DP = 120;
	/** DQ={@value} */
	public static final int DQ = 121;
	/** DR={@value} */
	public static final int DR = 122;
	/** DS={@value} */
	public static final int DS = 123;
	/** DT={@value} */
	public static final int DT = 124;
	/** DU={@value} */
	public static final int DU = 125;
	/** DV={@value} */
	public static final int DV = 126;
	/** DW={@value} */
	public static final int DW = 127;
	/** DX={@value} */
	public static final int DX = 128;
	/** DY={@value} */
	public static final int DY = 129;
	/** DZ={@value} */
	public static final int DZ = 130;
	/** FA={@value} */
	public static final int FA = 131;
	/** FB={@value} */
	public static final int FB = 132;
	/** FC={@value} */
	public static final int FC = 133;
	/** FD={@value} */
	public static final int FD = 134;
	/** FE={@value} */
	public static final int FE = 135;
	/** FF={@value} */
	public static final int FF = 136;
	/** FG={@value} */
	public static final int FG = 137;
	/** FH={@value} */
	public static final int FH = 138;
	/** FI={@value} */
	public static final int FI = 139;
	/** FJ={@value} */
	public static final int FJ = 140;
	/** FK={@value} */
	public static final int FK = 141;
	/** FL={@value} */
	public static final int FL = 142;
	/** FM={@value} */
	public static final int FM = 143;
	/** FN={@value} */
	public static final int FN = 144;
	/** FO={@value} */
	public static final int FO = 145;
	/** FP={@value} */
	public static final int FP = 146;
	/** FQ={@value} */
	public static final int FQ = 147;
	/** FR={@value} */
	public static final int FR = 148;
	/** FS={@value} */
	public static final int FS = 149;
	/** FT={@value} */
	public static final int FT = 150;
	/** FU={@value} */
	public static final int FU = 151;
	/** FV={@value} */
	public static final int FV = 152;
	/** FW={@value} */
	public static final int FW = 153;
	/** FX={@value} */
	public static final int FX = 154;
	/** FY={@value} */
	public static final int FY = 155;
	/** FZ={@value} */
	public static final int FZ = 156;
	/** GA={@value} */
	public static final int GA = 157;
	/** GB={@value} */
	public static final int GB = 158;
	/** GC={@value} */
	public static final int GC = 159;
	/** GD={@value} */
	public static final int GD = 160;
	/** GE={@value} */
	public static final int GE = 161;
	/** GF={@value} */
	public static final int GF = 162;
	/** GG={@value} */
	public static final int GG = 163;
	/** GH={@value} */
	public static final int GH = 164;
	/** GI={@value} */
	public static final int GI = 165;
	/** GJ={@value} */
	public static final int GJ = 166;
	/** GK={@value} */
	public static final int GK = 167;
	/** GL={@value} */
	public static final int GL = 168;
	/** GM={@value} */
	public static final int GM = 169;
	/** GN={@value} */
	public static final int GN = 170;
	/** GO={@value} */
	public static final int GO = 171;
	/** GP={@value} */
	public static final int GP = 172;
	/** GQ={@value} */
	public static final int GQ = 173;
	/** GR={@value} */
	public static final int GR = 174;
	/** GS={@value} */
	public static final int GS = 175;
	/** GT={@value} */
	public static final int GT = 176;
	/** GU={@value} */
	public static final int GU = 177;
	/** GV={@value} */
	public static final int GV = 178;
	/** GW={@value} */
	public static final int GW = 179;
	/** GX={@value} */
	public static final int GX = 180;
	/** GY={@value} */
	public static final int GY = 181;
	/** GZ={@value} */
	public static final int GZ = 182;
	/** HA={@value} */
	public static final int HA = 183;
	/** HB={@value} */
	public static final int HB = 184;
	/** HC={@value} */
	public static final int HC = 185;
	/** HD={@value} */
	public static final int HD = 186;
	/** HE={@value} */
	public static final int HE = 187;
	/** HF={@value} */
	public static final int HF = 188;
	/** HG={@value} */
	public static final int HG = 189;
	/** HH={@value} */
	public static final int HH = 190;
	/** HI={@value} */
	public static final int HI = 191;
	/** HJ={@value} */
	public static final int HJ = 192;
	/** HK={@value} */
	public static final int HK = 193;
	/** HL={@value} */
	public static final int HL = 194;
	/** HM={@value} */
	public static final int HM = 195;
	/** HN={@value} */
	public static final int HN = 196;
	/** HO={@value} */
	public static final int HO = 197;
	/** HP={@value} */
	public static final int HP = 198;
	/** HQ={@value} */
	public static final int HQ = 199;
	/** HR={@value} */
	public static final int HR = 200;
	/** HS={@value} */
	public static final int HS = 201;
	/** HT={@value} */
	public static final int HT = 202;
	/** HU={@value} */
	public static final int HU = 203;
	/** HV={@value} */
	public static final int HV = 204;
	/** HW={@value} */
	public static final int HW = 205;
	/** HX={@value} */
	public static final int HX = 206;
	/** HY={@value} */
	public static final int HY = 207;
	/** HZ={@value} */
	public static final int HZ = 208;
	/** IA={@value} */
	public static final int IA = 209;
	/** IB={@value} */
	public static final int IB = 210;
	/** IC={@value} */
	public static final int IC = 211;
	/** ID={@value} */
	public static final int ID = 212;
	/** IE={@value} */
	public static final int IE = 213;
	/** IF={@value} */
	public static final int IF = 214;
	/** IG={@value} */
	public static final int IG = 215;
	/** IH={@value} */
	public static final int IH = 216;
	/** II={@value} */
	public static final int II = 217;
	/** IJ={@value} */
	public static final int IJ = 218;
	/** IK={@value} */
	public static final int IK = 219;
	/** IL={@value} */
	public static final int IL = 220;
	/** IM={@value} */
	public static final int IM = 221;
	/** IN={@value} */
	public static final int IN = 222;
	/** IO={@value} */
	public static final int IO = 223;
	/** IP={@value} */
	public static final int IP = 224;
	/** IQ={@value} */
	public static final int IQ = 225;
	/** IR={@value} */
	public static final int IR = 226;
	/** IS={@value} */
	public static final int IS = 227;
	/** IT={@value} */
	public static final int IT = 228;
	/** IU={@value} */
	public static final int IU = 229;
	/** IV={@value} */
	public static final int IV = 230;
	/** IW={@value} */
	public static final int IW = 231;
	/** IX={@value} */
	public static final int IX = 232;
	/** IY={@value} */
	public static final int IY = 233;
	/** IZ={@value} */
	public static final int IZ = 234;
	/** JA={@value} */
	public static final int JA = 235;
	/** JB={@value} */
	public static final int JB = 236;
	/** JC={@value} */
	public static final int JC = 237;
	/** JD={@value} */
	public static final int JD = 238;
	/** JE={@value} */
	public static final int JE = 239;
	/** JF={@value} */
	public static final int JF = 240;
	/** JG={@value} */
	public static final int JG = 241;
	/** JH={@value} */
	public static final int JH = 242;
	/** JI={@value} */
	public static final int JI = 243;
	/** JJ={@value} */
	public static final int JJ = 244;
	/** JK={@value} */
	public static final int JK = 245;
	/** JL={@value} */
	public static final int JL = 246;
	/** JM={@value} */
	public static final int JM = 247;
	/** JN={@value} */
	public static final int JN = 248;
	/** JO={@value} */
	public static final int JO = 249;
	/** JP={@value} */
	public static final int JP = 250;
	/** JQ={@value} */
	public static final int JQ = 251;
	/** JR={@value} */
	public static final int JR = 252;
	/** JS={@value} */
	public static final int JS = 253;
	/** JT={@value} */
	public static final int JT = 254;
	/** JU={@value} */
	public static final int JU = 255;
	/** JV={@value} */
	// public static final int JV = 256;
}
